import pytest
import numpy as np
import cv2
from detector.temporal_flow import TemporalFlowDetector
from detector.physics_lighting import PhysicsLightingDetector
from detector.c2pa_watermark import C2PAWatermarkDetector
from detector.rppg_biological import RPPGBiologicalDetector
from detector.ensemble_evaluator import EnsembleEvaluator


def test_temporal_flow_smooth_motion():
    detector = TemporalFlowDetector()
    # Create smooth shifting frame sequence
    frames = []
    base = np.zeros((270, 480, 3), dtype=np.uint8)
    cv2.circle(base, (200, 130), 40, (200, 200, 200), -1)
    
    for i in range(5):
        f = base.copy()
        # Shift circle slightly by 2px per frame smoothly
        f = np.roll(f, i * 2, axis=1)
        frames.append(f)

    res = detector.analyze_burst(frames)
    assert "score" in res
    assert "motion_coherence" in res
    assert res["motion_coherence"] > 0.5


def test_physics_lighting_detector():
    detector = PhysicsLightingDetector()
    # Single uniform light source gradient
    frames = []
    for _ in range(3):
        f = np.zeros((300, 300, 3), dtype=np.uint8)
        for y in range(300):
            f[y, :] = int(y / 300.0 * 255)
        frames.append(f)

    res = detector.analyze_burst(frames)
    assert "lighting_consistency" in res
    assert "specular_symmetry" in res


def test_c2pa_watermark_detection():
    detector = C2PAWatermarkDetector()
    
    # Synthetic claim payload
    synthetic_payload = b"Sample metadata with c2pa manifest urn:c2pa: claim synthetic_content generated by sora"
    res_syn = detector.inspect_raw_bytes(synthetic_payload)
    assert res_syn["c2pa_present"] is True
    assert res_syn["synthetic_claim"] is True

    # Clean payload
    clean_payload = b"Standard image bytes without provenance"
    res_clean = detector.inspect_raw_bytes(clean_payload)
    assert res_clean["c2pa_present"] is False
    assert res_clean["synthetic_claim"] is False


def test_ensemble_evaluator_two_tiers():
    evaluator = EnsembleEvaluator(fps=10.0)
    
    # Generate 5 sample frames
    frames = []
    for i in range(5):
        f = np.full((256, 256, 3), 120 + i * 2, dtype=np.uint8)
        cv2.putText(f, f"Frame {i}", (30, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
        frames.append(f)

    # 1. Fast tier (<100ms)
    fast_res = evaluator.evaluate_fast_tier(frames[0])
    assert fast_res["tier"] == "fast"
    assert "ai_probability" in fast_res
    assert "badge_color" in fast_res
    assert fast_res["badge_color"] in ["GREEN", "AMBER", "RED"]

    # 2. Deep tier (comprehensive)
    deep_res = evaluator.evaluate_deep_tier(frames)
    assert deep_res["tier"] == "deep"
    assert "vectors" in deep_res
    assert "spatial_frequency" in deep_res["vectors"]
    assert "biological_rppg" in deep_res["vectors"]
    assert "temporal_optical_flow" in deep_res["vectors"]
    assert "physics_and_lighting" in deep_res["vectors"]
    assert "heatmap_boxes" in deep_res
    assert "status_label" in deep_res
